if not exists (select 1 from dbo.[Person])
begin

INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Martelle', N'Woodyer', 29, N'+30 728 979 6883', N'Kompóti', N'mwoodyer0@bing.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Uri', N'Belsher', 25, N'+351 529 141 8155', N'Macedo de Cavaleiros', N'ubelsher1@constantcontact.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Beltran', N'Spracklin', 40, N'+86 332 876 7195', N'Guantouzui', N'bspracklin2@tinypic.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Fannie', N'Dufaur', 21, N'+506 854 695 4887', N'Esquipulas', N'fdufaur3@a8.net')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Eda', N'Lumsdon', 38, N'+51 376 577 9599', N'Chinchaypujio', N'elumsdon4@google.com.hk')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Britt', N'Hassell', 31, N'+964 389 401 8494', N'Ad Diwaniyah', N'bhassell5@ted.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Simeon', N'Marquot', 50, N'+55 136 758 8081', N'Taboão da Serra', N'smarquot6@baidu.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Garold', N'Lichtfoth', 34, N'+48 544 283 7852', N'Wola Uhruska', N'glichtfoth7@facebook.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Malory', N'Odney', 34, N'+46 697 444 1016', N'Gislaved', N'modney8@alibaba.com')
INSERT [dbo].[Person] ([FirstName], [LastName], [Age], [Phone], [City], [Email]) VALUES ('Paulie', N'Braybrooke', 35, N'+63 803 900 0554', N'Sinacaban', N'pbraybrooke9@paginegialle.it')

INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Administrative Officer', N'Chiropractic Manipulation of Abdomen, Direct Visceral', 1)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Professor', N'Extirpation of Matter from Abd Subcu/Fascia, Perc Approach', 1)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Help Desk Technician', N'Drainage of Right Pleural Cavity, Percutaneous Approach', 2)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Food Chemist', N'Sinus Vert Axis Rotation Assess w Vestib/Balance Equip', 2)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Chemical Engineer', N'Drainage of Right Eye, External Approach, Diagnostic', 3)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('General Manager', N'Fluoroscopy of Gallbladder using Other Contrast', 3)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Physical Therapy Assistant', N'Removal of Synthetic Substitute from Bladder, Open Approach', 4)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Design Engineer', N'Drainage of Left Lacrimal Duct with Drain Dev, Via Opening', 4)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Accountant IV', N'Bypass L Popl Art to Peron Art w Nonaut Sub, Perc Endo', 5)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Account Representative II', N'Revision of Synth Sub in Facial Bone, Extern Approach', 5)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('VP Quality Control', N'MRI of R Low Extrem Art using Oth Contrast', 6)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Senior Editor', N'Fusion Occip Jt w Autol Sub, Post Appr A Col, Perc', 6)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Safety Technician II', N'Replace Ant Neck Subcu/Fascia w Nonaut Sub, Open', 7)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Safety Technician I', N'Resection of Middle Esophagus, Via Opening', 7)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('VP Product Management', N'Revision of Drainage Device in T-lum Jt, Perc Endo Approach', 8)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Quality Control Specialist', N'Drainage of Left Hepatic Duct, Perc Endo Approach', 8)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Environmental Specialist', N'Release Left Internal Mammary Lymphatic, Open Approach', 9)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Senior Financial Analyst', N'Destruction of Thoracic Sympathetic Nerve, Perc Approach', 9)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Recruiting Manager', N'Bypass 1 Cor Art from Aorta with Autol Vn, Open Approach', 10)
INSERT [dbo].[Interest] ([Title], [Description], [PersonId]) VALUES ('Quality Control Specialist', N'Dilate R Basilic Vein w Intralum Dev, Perc Endo', 10)

INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://go.com/lorem/vitae.html', 1, 1)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://yahoo.com/porttitor/id/consequat/in/consequat/ut.json', 1, 1)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://posterous.com/tortor/quis/turpis/sed/ante/vivamus/tortor.png', 1, 1)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://newyorker.com/ut/massa/quis/augue/luctus/tincidunt.json', 1, 2)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://pbs.org/fusce/posuere/felis.xml', 1, 2)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://businesswire.com/nam/tristique/tortor/eu/pede.xml', 1, 2)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://goo.ne.jp/sapien.jpg', 2, 3)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://g.co/lobortis/est/phasellus/sit/amet.json', 2, 3)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://usgs.gov/massa/id/lobortis.jpg', 2, 3)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://cam.ac.uk/in/faucibus/orci/luctus/et/ultrices.jpg', 2, 4)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://jiathis.com/amet/justo/morbi.js', 2, 4)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://latimes.com/turpis/sed/ante/vivamus.jsp', 2, 4)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://go.com/quis/turpis/sed.jsp', 3, 5)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://utexas.edu/ipsum/integer/a/nibh/in.xml', 3, 5)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://yellowpages.com/ante/vestibulum/ante/ipsum/primis/in/faucibus.json', 3, 5)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://xrea.com/ante/nulla/justo/aliquam/quis/turpis.html', 3, 6)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://unicef.org/rhoncus/aliquet.jpg', 3, 6)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://sun.com/donec/diam/neque/vestibulum/eget/vulputate.json', 3, 6)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://usgs.gov/sociis/natoque/penatibus.xml', 4, 7)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://hubpages.com/consectetuer.js', 4, 7)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://de.vu/ipsum/ac/tellus/semper/interdum.html', 4, 7)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://odnoklassniki.ru/in/hac/habitasse.png', 4, 8)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://paginegialle.it/id/consequat/in/consequat/ut/nulla.xml', 4, 8)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://chron.com/non/mi/integer.aspx', 4, 8)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://123-reg.co.uk/in/faucibus/orci/luctus/et.png', 5, 9)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://rakuten.co.jp/felis/eu/sapien/cursus/vestibulum/proin/eu.html', 5, 9)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://e-recht24.de/turpis.js', 5, 9)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://java.com/sed/nisl.jpg', 5, 10)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://tmall.com/parturient.aspx', 5, 10)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://seesaa.net/odio/condimentum/id/luctus.jsp', 5, 10)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://oaic.gov.au/bibendum/morbi/non/quam/nec/dui.jpg', 6, 11)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://cafepress.com/eu/felis/fusce.png', 6, 11)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://mapquest.com/orci/mauris/lacinia/sapien/quis/libero/nullam.html', 6, 11)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://reverbnation.com/vel/augue/vestibulum/rutrum/rutrum.json', 6, 12)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://gov.uk/justo/nec/condimentum/neque/sapien.html', 6, 12)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://prweb.com/risus/auctor/sed/tristique/in/tempus.jpg', 6, 12)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://scientificamerican.com/diam/neque.png', 7, 13)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://npr.org/tortor/sollicitudin/mi.aspx', 7, 13)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://altervista.org/non.html', 7, 13)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://abc.net.au/amet/sapien/dignissim/vestibulum/vestibulum/ante/ipsum.json', 7, 14)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://theglobeandmail.com/risus/auctor/sed/tristique/in.html', 7, 14)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://accuweather.com/parturient/montes/nascetur.png', 7, 14)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://behance.net/eget/eleifend/luctus.html', 8, 15)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://ask.com/eu/interdum.aspx', 8, 15)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://rambler.ru/erat/fermentum/justo/nec.aspx', 8, 15)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://php.net/congue/risus.jpg', 8, 16)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://bbc.co.uk/in/felis/donec.js', 8, 16)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://networkadvertising.org/erat/quisque/erat/eros/viverra.jsp', 8, 16)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://bloomberg.com/vulputate/elementum/nullam/varius/nulla.json', 9, 17)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://bigcartel.com/lectus/in/est.json', 9, 17)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://theglobeandmail.com/non/quam/nec/dui.js', 9, 17)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://washingtonpost.com/quis/orci/nullam/molestie/nibh.aspx', 9, 18)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://vk.com/eget/elit/sodales/scelerisque.js', 9, 18)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://quantcast.com/odio/odio/elementum/eu/interdum.png', 9, 18)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://google.com.br/condimentum/neque/sapien.png', 10, 19)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://prlog.org/pretium.jpg', 10, 19)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://example.com/sed/augue/aliquam.js', 10, 19)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('https://theguardian.com/suspendisse/potenti/in/eleifend/quam/a.xml', 10, 20)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://dot.gov/aliquet/maecenas/leo.png', 10, 20)
INSERT [dbo].[Link] ([Url], [PersonId], [InterestId]) VALUES ('http://joomla.org/congue/diam/id/ornare.js', 10, 20)


end